server:
  port: 9092

spring:
  amqp:
    deserialization:
      trust:
        all: true
  rabbitmq:
    host: localhost
    port: 5672
    username: BilgeAdmin
    password: Aa123456
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfileDB
      username: defaultUser
      password: bilge!*123

usermicroservice:
  redis:
    host: localhost
    port: 6379